---
common_pkgs_pacman:
  install:
    - 7zip
    - bind # nslookup, dig
    - bluez
    - bluez-utils
    - brightnessctl
    - btop
    - chromium
    - curl
    - dmidecode
    - dnsmasq
    - dosfstools # mkfs.vfat
    - dotnet-sdk
    - exfat-utils # mkfs.exfat
    - fastfetch
    - fd
    - file
    - fzf
    - ghostscript
    - gimp
    - github-cli
    - imagemagick
    - jq
    - libreoffice-still
    - nmap
    - noto-fonts-emoji
    - ntfs-3g # ntfs mount
    - ntfsprogs # mkfs.ntfs
    - openssh
    - openvpn
    - pdftk
    - pipewire
    - pipewire-alsa
    - pipewire-audio
    - pipewire-jack
    - pipewire-pulse
    - pipewire-session-manager
    - poppler
    - pulsemixer
    - radvd
    - ripgrep
    - rsync
    - sof-firmware
    - thunar
    - tigervnc
    - tree
    - unzip
    - usbmuxd
    - usbutils
    - vim
    - wdisplays
    - wget
    - zbar
    - zip
    - zoxide
  remove: []
  remove_regex: []
  remove_modified_configs: false
